
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run: docker build . -t deciphernow/k8s-waiter
      - run: docker push deciphernow/k8s-waiter

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master